#! /usr/bin/python3
"""db_gen.py — 从 out/dist 生成文章数据库（SQLite 方言，确定性输出）。

用法:
  db_gen.py --dist <out/dist> --manifest <out/dist/manifest.json>
            --out-sql <dir>          # 写 schema.sql + data.sql（供远端 make push 建库）
            [--out-db <path>]        # 顺带用相同内容建本地 .db（开发预览 9999 用）
            [--manifest-sha <sha>]   # 传入 repo manifest -r 快照哈希（缺省自动取）

设计（见 references/deploy-impl-plan.md）:
  * pages(url PK, file_path, title, kind)  — 路由/元信息
  * pages_fts(url,title,body) FTS5 内嵌正文, tokenize='trigram' — 中文任意 3+ 字子串命中 + snippet()
  * meta — schema_version / manifest_sha / dialect
  * 确定性: 遍历按 url 稳定排序、不写时间戳；同一输入多次生成 hash 一致
    （用户 2026-09-02 硬性要求：产物 hash 与 repo manifest 快照一一对应、删除后重编译仍一致）
"""

import argparse
import hashlib
import html as htmllib
import json
import os
import re
import subprocess
import sys

SCHEMA_VERSION = "1"

TITLE_RE = re.compile(r"(?is)<h[1][^>]*>(.*?)</h\1>")
STRIP_RE = re.compile(r"(?is)<(script|style|head|nav)[^>]*>.*?</\1>")
BR_RE = re.compile(r"(?is)<br\s*/?>")
BLOCK_RE = re.compile(r"(?is)</(p|h[1-6]|div|li|tr|th|td|blockquote|pre|section|article)>")
TAG_RE = re.compile(r"(?is)<[^>]+>")
WS_RE = re.compile(r"[ \t\xa0\u3000]+")
NL_RE = re.compile(r"\n\s*\n+")


def html_to_text(frag):
    """纯 body 片段/完整文档 → 可读纯文本（保留行结构，供 snippet 上下文）。"""
    s = STRIP_RE.sub(" ", frag)
    s = BR_RE.sub("\n", s)
    s = BLOCK_RE.sub("\n", s)
    s = TAG_RE.sub("", s)
    s = htmllib.unescape(s)
    s = WS_RE.sub(" ", s)
    s = NL_RE.sub("\n", s)
    return s.strip()


def clean_title(raw):
    s = TAG_RE.sub("", raw)
    return WS_RE.sub(" ", htmllib.unescape(s)).strip() or "未命名文章"


def extract_title(frag):
    m = TITLE_RE.search(frag)
    return clean_title(m.group(1)) if m else "未命名文章"


def collect_pages(dist_dir, manifest):
    """遍历 manifest 树（稳定排序），产出文章记录 [url, file_path, kind]。file 形如 articles/x/index.html"""
    pages = []

    def walk(node, kind_default):
        for name in sorted(node.keys()):
            meta = node[name]
            file_rel = meta.get("file")
            if file_rel:
                pages.append({
                    "file_path": file_rel,
                    "kind": meta.get("type", kind_default),
                })
            if "children" in meta:
                walk(meta["children"], kind_default)
            elif "nodes" in meta:
                walk(meta["nodes"], kind_default)

    walk(manifest, "md")
    # 兜底：manifest 可能不含某些 html（如 index.html 主题页未入 manifest），再扫 articles 补漏
    seen = {p["file_path"] for p in pages}
    for root, _, files in sorted(os.walk(os.path.join(dist_dir, "articles"))):
        if "index.html" in files and "index.md" not in files:
            rel = os.path.relpath(os.path.join(root, "index.html"), dist_dir).replace(os.sep, "/")
            if rel not in seen:
                seen.add(rel)
                pages.append({"file_path": rel, "kind": "html"})
    pages.sort(key=lambda p: p["file_path"])
    return pages


def load_manifest(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def default_manifest_sha():
    """取 repo manifest -r 输出的 sha256（确定性锚点；失败则 None，容忍）。"""
    try:
        out = subprocess.run(["repo", "manifest", "-r", "-o", "-"],
                             capture_output=True, text=True, timeout=30)
        if out.returncode == 0:
            return hashlib.sha256(out.stdout.encode("utf-8")).hexdigest()
    except Exception:
        pass
    return None


def render_sql(pages, dist_dir, manifest_sha):
    lines = [
        "-- wblog article database (generated by db_gen.py, deterministic)",
        "-- dialect: sqlite",
        "PRAGMA journal_mode=WAL;",
        "BEGIN;",
        "DROP TABLE IF EXISTS meta;",
        "DROP TABLE IF EXISTS pages_fts;",
        "DROP TABLE IF EXISTS pages;",
        "CREATE TABLE pages (",
        "  url        TEXT PRIMARY KEY,",
        "  file_path  TEXT NOT NULL,",
        "  title      TEXT NOT NULL,",
        "  kind       TEXT",
        ");",
        "CREATE TABLE meta (k TEXT PRIMARY KEY, v TEXT);",
        "INSERT INTO meta VALUES ('schema_version', '%s');"
        % SCHEMA_VERSION,
    ]
    if manifest_sha:
        lines.append("INSERT INTO meta VALUES ('manifest_sha', '%s');" % manifest_sha)
    lines.append("INSERT INTO meta VALUES ('dialect', 'sqlite');")
    # FTS5 内嵌正文（唯一正文副本）；snippet 直接可用，无外连+trigram 限制
    lines.append(
        "CREATE VIRTUAL TABLE pages_fts USING fts5("
        "url UNINDEXED, title, body, tokenize='trigram');"
    )
    lines.append("COMMIT;")
    schema = "\n".join(lines) + "\n"

    data = ["BEGIN;"]
    for p in pages:
        html_path = os.path.join(dist_dir, p["file_path"])
        try:
            with open(html_path, encoding="utf-8") as f:
                frag = f.read()
        except OSError:
            continue
        title = extract_title(frag)
        body = html_to_text(frag)
        url = "/" + p["file_path"]
        data.append("INSERT INTO pages (url, file_path, title, kind) VALUES (%s, %s, %s, %s);"
                    % (sql_str(url), sql_str(p["file_path"]), sql_str(title), sql_str(p["kind"])))
        data.append("INSERT INTO pages_fts (url, title, body) VALUES (%s, %s, %s);"
                    % (sql_str(url), sql_str(title), sql_str(body)))
    data.append("COMMIT;")
    return schema, "\n".join(data) + "\n"


def sql_str(s):
    return "'" + s.replace("'", "''") + "'"


def build_db(schema, data, db_path):
    import sqlite3
    if os.path.exists(db_path):
        os.remove(db_path)
    conn = sqlite3.connect(db_path)
    conn.executescript(schema)
    conn.executescript(data)
    conn.commit()
    conn.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dist", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--out-sql", required=True)
    ap.add_argument("--out-db")
    ap.add_argument("--manifest-sha")
    args = ap.parse_args()

    manifest = load_manifest(args.manifest)
    pages = collect_pages(args.dist, manifest)
    manifest_sha = args.manifest_sha or default_manifest_sha()
    schema, data = render_sql(pages, args.dist, manifest_sha)

    os.makedirs(args.out_sql, exist_ok=True)
    with open(os.path.join(args.out_sql, "schema.sql"), "w", encoding="utf-8") as f:
        f.write(schema)
    with open(os.path.join(args.out_sql, "data.sql"), "w", encoding="utf-8") as f:
        f.write(data)
    print(f"db_gen: {len(pages)} pages -> {args.out_sql}/schema.sql + data.sql"
          + (f", manifest_sha={manifest_sha[:12]}" if manifest_sha else ", (no manifest_sha)"))

    if args.out_db:
        build_db(schema, data, args.out_db)
        print(f"db_gen: local db -> {args.out_db}")


if __name__ == "__main__":
    main()
